"""Shared visual style for all refusal-axis figures.

Tokens extracted from web/src/tokens.js (read-only; do not edit this file
to change the site palette -- change tokens.js and re-run the figures).

Usage::

    from refusal_decomposition.viz._style import (
        SITE_PALETTE,
        DOMAIN_COLOURS,
        apply_site_style,
        redblue_cmap,
        save_publication_figure,
    )

    apply_site_style()   # call once per script, before any figure creation
    cmap = redblue_cmap()
    save_publication_figure(fig, Path("out/fig_a.png"))
"""

from __future__ import annotations

import shutil
from pathlib import Path

import matplotlib
import matplotlib.pyplot as plt
from matplotlib.colors import LinearSegmentedColormap

# ---------------------------------------------------------------------------
# Site palette -- extracted verbatim from web/src/tokens.js
# ---------------------------------------------------------------------------
SITE_PALETTE: dict[str, str] = {
    # Surfaces and backgrounds
    "bg": "#F4F4F4",
    "surface": "#FFFFFF",
    "surfaceAlt": "#FAFAFA",
    "border": "#E5E5E5",
    # Text
    "text": "#0A0A0A",
    "body": "#262626",
    "muted": "#737373",
    "stepNumber": "#525252",
    # Accent
    "orange": "#CC785C",  # Anthropic clay-orange
    # Refusal-axis diverging ends (Lu et al. RedBlue scale)
    "refuse": "#1d3557",   # navy -- strong refusal
    "comply": "#e63946",   # red -- compliance / no refusal
    "highlight": "#457b9d",  # muted teal-blue secondary accent
    # Neutral mid-point for colourmap
    "neutral": "#f7f7f7",
}

# ---------------------------------------------------------------------------
# Domain colours -- Okabe-Ito colourblind-safe palette (tokens.js § domains)
# Key: domain id as used in Python data (matches manifest domain field)
# ---------------------------------------------------------------------------
DOMAIN_COLOURS: dict[str, str] = {
    "safety": "#D55E00",            # domainSafety
    "ethical": "#CC79A7",           # domainEthical
    "legal": "#E69F00",             # domainLegal
    "privacy": "#0072B2",           # domainPrivacy
    "identity_boundary": "#009E73", # domainIdentity
    "capability_boundary": "#56B4E9",  # domainCapability
}

# Human-readable short labels (canonical display order matches tokens.js)
DOMAIN_LABELS: dict[str, str] = {
    "safety": "Safety",
    "ethical": "Ethical",
    "legal": "Legal",
    "privacy": "Privacy",
    "identity_boundary": "Identity",
    "capability_boundary": "Capability",
}

# ---------------------------------------------------------------------------
# Font family -- Inter with graceful fallback to DejaVu Sans.
# Do NOT crash on missing fonts; matplotlib silently falls back if the first
# family is unavailable.
# ---------------------------------------------------------------------------
_FONT_FAMILY = ["Inter", "DejaVu Sans", "Helvetica", "Arial", "sans-serif"]


# ---------------------------------------------------------------------------
# apply_site_style
# ---------------------------------------------------------------------------
def apply_site_style() -> None:
    """Set matplotlib rcParams to match the site's visual identity.

    Call once at the top of each figure script, before creating any figure.
    Replaces per-script rcParams blocks.
    """
    matplotlib.rcParams.update(
        {
            # Background
            "figure.facecolor": SITE_PALETTE["surface"],
            "axes.facecolor": SITE_PALETTE["surface"],
            "savefig.facecolor": SITE_PALETTE["surface"],
            # Text
            "text.color": SITE_PALETTE["body"],
            "axes.labelcolor": SITE_PALETTE["body"],
            "xtick.color": SITE_PALETTE["muted"],
            "ytick.color": SITE_PALETTE["muted"],
            # Font -- single family throughout; no serif/LaTeX variants
            "font.family": "sans-serif",
            "font.sans-serif": _FONT_FAMILY,
            "text.usetex": False,
            # Sizes
            "font.size": 9,
            "axes.titlesize": 11,
            "axes.labelsize": 9,
            "xtick.labelsize": 8,
            "ytick.labelsize": 8,
            "legend.fontsize": 8,
            # Spines and ticks
            "axes.linewidth": 0.6,
            "axes.spines.top": False,
            "axes.spines.right": False,
            "xtick.major.width": 0.6,
            "ytick.major.width": 0.6,
            "xtick.minor.visible": False,
            "ytick.minor.visible": False,
            "axes.edgecolor": SITE_PALETTE["border"],
            # Grid
            "axes.grid": False,
            "grid.color": SITE_PALETTE["border"],
            "grid.linewidth": 0.4,
            "grid.alpha": 0.6,
            # Legend
            "legend.framealpha": 0.92,
            "legend.edgecolor": SITE_PALETTE["border"],
            "legend.fancybox": False,
            # Lines
            "lines.linewidth": 1.8,
            "patch.linewidth": 0.5,
        }
    )


# ---------------------------------------------------------------------------
# redblue_cmap
# ---------------------------------------------------------------------------
def redblue_cmap(name: str = "refusal_redblue") -> LinearSegmentedColormap:
    """Return the site's diverging RedBlue colormap.

    Maps:
      0.0 -- comply (#e63946, red, no refusal)
      0.5 -- neutral (#f7f7f7, off-white)
      1.0 -- refuse  (#1d3557, navy, strong refusal)

    This matches the site token values and Lu et al. (2026) colour convention.
    """
    return LinearSegmentedColormap.from_list(
        name,
        [SITE_PALETTE["comply"], SITE_PALETTE["neutral"], SITE_PALETTE["refuse"]],
        N=256,
    )


# ---------------------------------------------------------------------------
# save_publication_figure
# ---------------------------------------------------------------------------
def save_publication_figure(
    fig: plt.Figure,
    out_path: Path,
    *,
    dpi: int = 200,
    also_pdf: bool = True,
    web_copy_dir: Path | None = None,
    is_3d: bool = False,
) -> None:
    """Save a figure as PNG (and optionally PDF) with consistent settings.

    Parameters
    ----------
    fig:
        The matplotlib Figure to save.
    out_path:
        Destination PNG path (extension .png will be added or enforced).
    dpi:
        Output resolution. 200 is sufficient for web; use 300 for print.
    also_pdf:
        If True, also saves a PDF alongside the PNG.
    web_copy_dir:
        If given, copy the PNG to this directory (e.g. web/public/figures/...).
    is_3d:
        If True, use pad_inches=0.4 instead of bbox_inches='tight', which
        prevents matplotlib from clipping 3D axis labels (a known issue with
        Axes3D and bbox_inches='tight').
    """
    out_path = Path(out_path).with_suffix(".png")
    out_path.parent.mkdir(parents=True, exist_ok=True)

    save_kwargs: dict = {"dpi": dpi}
    if is_3d:
        # bbox_inches='tight' clips zlabel on 3D axes; use pad_inches instead
        save_kwargs["pad_inches"] = 0.4
    else:
        save_kwargs["bbox_inches"] = "tight"

    fig.savefig(out_path, **save_kwargs)

    if also_pdf:
        pdf_path = out_path.with_suffix(".pdf")
        pdf_kwargs = dict(save_kwargs)
        pdf_kwargs.pop("dpi", None)  # PDF is vector; dpi is irrelevant
        fig.savefig(pdf_path, **pdf_kwargs)

    if web_copy_dir is not None:
        web_copy_dir = Path(web_copy_dir)
        web_copy_dir.mkdir(parents=True, exist_ok=True)
        shutil.copy2(out_path, web_copy_dir / out_path.name)
